apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "x-clone.fullname" . }}-secrets
  labels:
    {{- include "x-clone.labels" . | nindent 4 }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: x-clone-secrets
    creationPolicy: Owner
  data:
  - secretKey: DATABASE_URL
    remoteRef:
      key: {{ .Values.secrets.awsSecretName }}
      property: DATABASE_URL
  - secretKey: NEXTAUTH_SECRET
    remoteRef:
      key: {{ .Values.secrets.awsSecretName }}
      property: NEXTAUTH_SECRET
  - secretKey: NEXTAUTH_URL
    remoteRef:
      key: {{ .Values.secrets.awsSecretName }}
      property: NEXTAUTH_URL
