apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://charts.jetstack.io
    chart: cert-manager
    targetRevision: v1.13.3
    helm:
      parameters:
      - name: installCRDs
        value: "true"
      - name: global.leaderElection.namespace
        value: cert-manager
      values: |
        tolerations:
          - key: "node-type"
            operator: "Equal"
            value: "system"
            effect: "NoSchedule"
        webhook:
          tolerations:
            - key: "node-type"
              operator: "Equal"
              value: "system"
              effect: "NoSchedule"
        cainjector:
          tolerations:
            - key: "node-type"
              operator: "Equal"
              value: "system"
              effect: "NoSchedule"
  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
