apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: rds-credentials
  namespace: tbyte
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: rds-credentials
    creationPolicy: Owner
    template:
      data:
        host: tbyte-dev-postgres.chskyoeag2m9.eu-central-1.rds.amazonaws.com
        port: "5432"
        dbname: tbyte
        username: "{{ .username }}"
        password: "{{ .password }}"
  dataFrom:
  - extract:
      key: arn:aws:secretsmanager:eu-central-1:575491070504:secret:rds!db-8c6b075e-ea26-4c71-a46d-5921cead40b9-pzkz47
