apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: rds-credentials
  namespace: tbyte
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: rds-credentials
    creationPolicy: Owner
  dataFrom:
  - extract:
      key: arn:aws:secretsmanager:eu-central-1:575491070504:secret:rds!db-ba5d22ee-e8e3-4d34-b010-0020ebce76ac-lZbCaa
  data:
  - secretKey: host
    remoteRef:
      key: literal
      property: tbyte-dev-postgres.chskyoeag2m9.eu-central-1.rds.amazonaws.com
  - secretKey: port
    remoteRef:
      key: literal
      property: "5432"
  - secretKey: dbname
    remoteRef:
      key: literal
      property: tbyte
