apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: inventory-service-monitor
  namespace: inventory-service
  labels:
    app: inventory-service
spec:
  selector:
    matchLabels:
      app: inventory-service
  endpoints:
  - port: http
    path: /metrics
    interval: 30s
