{{- if and .Values.frontend.enabled .Values.frontend.autoscaling.enabled }}
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: {{ include "tbyte-microservices.fullname" . }}-frontend
  labels:
    {{- include "tbyte-microservices.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
spec:
  scaleTargetRef:
    apiVersion: argoproj.io/v1alpha1
    kind: Rollout
    name: {{ include "tbyte-microservices.fullname" . }}-frontend
  minReplicaCount: {{ .Values.frontend.autoscaling.minReplicas }}
  maxReplicaCount: {{ .Values.frontend.autoscaling.maxReplicas }}
  advanced:
    horizontalPodAutoscalerConfig:
      behavior:
        scaleDown:
          stabilizationWindowSeconds: 300  # Slower scale-down during rollouts
          policies:
          - type: Percent
            value: 10
            periodSeconds: 60
        scaleUp:
          stabilizationWindowSeconds: 60   # Allow controlled scale-up
          policies:
          - type: Percent
            value: 50
            periodSeconds: 30
  triggers:
  - type: cpu
    metricType: Utilization
    metadata:
      value: "{{ .Values.frontend.autoscaling.targetCPUUtilizationPercentage | default 70 }}"
  - type: memory
    metricType: Utilization  
    metadata:
      value: "{{ .Values.frontend.autoscaling.targetMemoryUtilizationPercentage | default 80 }}"
{{- end }}
